# -*- coding: utf-8 -*-
"""Week8assgn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cb4wOINbaquz8vtsRpUZ7sJgk9ruy3WI
"""

import streamlit as st
import numpy as np

def largest_num(num1, num2, num3):
    if num1 >= num2 and num1 >= num3:
        return num1
    elif num2 >= num1 and num2 >= num3:
        return num2
    else:
        return num3

st.title("Find the Largest Among Three Numbers")
num1 = st.number_input("Enter the first number:")
num2 = st.number_input("Enter the second number:")
num3 = st.number_input("Enter the third number:")
if st.button("Find the Largest"):
    result = largest_num(num1, num2, num3)
    st.success("The largest number is: {}".format(result))

